apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app.name }}
spec:
  ports:
    - port: {{ .Values.app.port }}
      nodePort: {{ .Values.app.nodePort }}
  selector:
    app: {{ .Values.app.name }}
  type: NodePort
